---
- name: Enable firewall and default input policy
  ufw: state=enabled direction=routed policy=allow

- name: Allow HTTP
  ufw: rule=allow port=80 proto=tcp

- name: Allow HTTPS
  ufw: rule=allow port=443 proto=tcp

- name: Allow SSH
  ufw: rule=allow port=22 proto=tcp
