---
- name: Install packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items:
  - {name: 'git-core'}
  - {name: 'ufw'}
  - {name: 'software-properties-common'}
  - {name: 'python3'}
  - {name: 'python3-pip'}
